# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Pocket-Chef' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pocket-Chef
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
# for Analytics without IDFA collection capability

# add pods for any other desired Firebase products
pod 'Firebase/Auth'
pod 'FirebaseUI'
pod 'Firebase/Functions'
pod 'Firebase/Database'
# https://firebase.google.com/docs/ios/setup#available-pods
end
